name: master

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

    paths:
      - "scripts/**"
      - ".github/workflows/master.yaml"
      - "tests/**"

env:
  # Environment
  CI_ENVIRONMENT: production

jobs:
  test:
    name: Test
    env:
      CI_PACKAGE_NAME: "web"

      # Container Registry
      CI_REPOSITORY_NAME: "sydnod-ci"
      CI_REPOSITORY_HOSTNAME: "${{ secrets.CI_REPOSITORY_HOSTNAME }}"
      CI_REPOSITORY_USERNAME: "${{ secrets.CI_REPOSITORY_USERNAME }}"
      CI_REPOSITORY_PASSWORD: "${{ secrets.CI_REPOSITORY_PASSWORD }}"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      # Bootstrap
      - name: CI Bootstrap
        run: chmod -R +x ./scripts && ./scripts/bootstrap.sh

      # Test Bootstrap CI script
      - name: CI Bootstrap Tests
        run: chmod -R +x ./tests/scripts && ./tests/scripts/bootstrap.sh

      # Set the target AKS cluster.
      - name: Login to Kubernetes
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.CI_KUBE_CONFIG }}

      # Login to CR
      - name: Login to Docker Container Registry (CR)
        uses: Azure/docker-login@v1
        with:
          login-server: ${{ env.CI_REPOSITORY_HOSTNAME }}
          username: ${{ env.CI_REPOSITORY_USERNAME }}
          password: ${{ env.CI_REPOSITORY_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build
          -f ./tests/Dockerfile
          -t "${CI_REPOSITORY_IMAGE_PATH_FULL}"
          --build-arg CI_ENVIRONMENT=${{ env.CI_ENVIRONMENT }}
          --build-arg CI_COMMIT_SHA_SHORT=${{ env.CI_COMMIT_SHA_SHORT }}
          ./tests/src

      # Push Docker image
      - name: Push Docker image to CR
        run: docker push ${CI_REPOSITORY_IMAGE_PATH_FULL}
